name: CI

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  run-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest==8.2.2 typing==3.7.4

      - name: Run Unit Tests
        run: pytest
