name: CI-Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  run-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
        
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run Unit Tests and Generate XML Report
        id: run-tests
        run: |
          REPORT_PATH="reports/pytest-report-$(date +"%Y%m%d_%H%M%S").xml"
          pytest --junitxml=$REPORT_PATH
          echo "Generated XML report at $REPORT_PATH"
          echo "::set-output name=report_path::$REPORT_PATH"  # Set the output variable

      - name: Upload XML Report
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: pytest-reports
          path: ${{ steps.run-tests.outputs.report_path }}